### ISSUE TITLE
Server won't start with this mod (1.18.2)

### ISSUE THREAD

**Issue by Sandrituky** [omnixerio/devices-mod#73] opened 2023-05-12 01:58 UTC
**To Reproduce**
1. Launch server and wait
2. Seeing the server log is stopped
3. Check crash-report

**Logs**
Add an optional log file to the issue, this helps developers to find out when it went wrong.
[latest.log](https://github.com/Ultreon/devices-mod/files/11457982/latest.log)

**Crash report**
[crash-2023-05-12_03.47.12-fml.txt](https://github.com/Ultreon/devices-mod/files/11457979/crash-2023-05-12_03.47.12-fml.txt)

Add a crash report to the issue, this is essential for developers to know what went wrong.

**Please complete the following information:**
 - OS: Windows 10
 - Minecraft version: 1.18.2
 - Devices Mod Version: 0.5.0.1
 - Architectury API Version: 4.11.93

**FOR FORGE:**
 - Forge version: 40.2.2

**Additional context**
There's something that catchs my attention on crash-report log:

forge-devices-0.5.0.1.jar                         |Devices Mod                   |devices                       |0.5.0.1             |ERROR     |Manifest: NOSIGNATURE
devices-merged-0.5.0.1.jar                        |Devices Mod Wrapper           |devices_forge                 |1                   |SIDED_SETU|Manifest: NOSIGNATURE

The mod I've downloaded is devices-merged-0.5.0.1.jar, I don't have any called forge-devices, I don't know why it seems like duplicated or something like that. 

The server will load sucessfully when I remove this mod. 
The client always loads sucessfully with this mod. I can even enter in my server, which doesn't have the mod. I'm confused :S 

I hope you can help me :)

**Additional mods used**
[myMods.txt](https://github.com/Ultreon/devices-mod/files/11458024/myMods.txt)

**Comment by QboiDev** [comment] 2023-05-12 06:47
Duplicate of #64

**Comment by Sandrituky** [comment] 2023-05-12 09:29
> Duplicate of #64

True! Sorry! Close mine or whichever you want!

**Closed as not planned** 2023-05-12 09:29 UTC
Labels: duplicate, crash
