### ISSUE TITLE
Game crash. (logs and crash report)

### ISSUE THREAD

**Issue by Problemreported** [omnixerio/devices-mod#37] opened 2022-11-02 21:29 UTC
### Sorry I am dumb I forgot we needed the api mod

**To Reproduce**
1. Install both mods listed below
2. Install forge version listed below
3. Make sure mc version is right
4. Launch 
5. Game crash

**Logs**
https://paste.ee/p/87mhd < log (Uploaded from MultiMC

**Crash report**
https://paste.ee/p/lW6YB

**Please complete the following information:**
 - OS: Windows 10
 - Minecraft version 1.19.2
 - Devices Mod Version:  0.5.4-157
 - Architectury API Version: wait do we need this

**FOR FABRIC:**
(Fabric unused)

**FOR FORGE:**
 - Forge version 43.1.47
 
**Additional context**

**Additional mods used**
Backpacked 2.1.10 by MrCrayfish

EDIT: I AM DUMB. I forgot we needed the required api mod

**Comment by Jab125** [comment] 2022-11-02 21:54
If the issue is resolved close the issue

**Closed as completed by Jab125** 2022-11-02 21:54 UTC
Labels: crash
